title: Hacktoberfest Swag List
logo: /img/Hacktoberfest_19.png
description: There are many companies giving out free swag for Hacktoberfest and this list seeks to find them all!
show_downloads: false
url: "https://hacktoberfestswaglist.com"
google_analytics: "UA-129265975-1"
remote_theme: "pages-themes/minimal"
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
include:
  - CONTRIBUTING.md
  
head_scripts:
  - /js/scroll_to_up.js
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME
repository: "crweiner/hacktoberfest-swag-list"
