title: Hacktoberfest Swag List IS WONDERFULL.......
logo: /img/Hacktoberfest_20.jpg
description: There are many companies giving out free swag for Hacktoberfest and this list seeks to find them all!
show_downloads: false
url: "https://hacktoberfestswaglist.com"
google_analytics: "UA-129265975-1"
remote_theme: "pages-themes/minimal"
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-remote-theme
include:
  - CONTRIBUTING.md
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSED
  - CNAME
repository: "crweiner/hacktoberfest-swag-list"
