# Project information
site_name: "Hacktoberfest Swag List 2023"
site_description: "Connecting contributors to open-source projects during Hacktoberfest"
site_author: "crweiner"
site_url: "https://hacktoberfestswaglist.com"

site_name: Hacktoberfest Swag List
docs_dir: "docs"
theme:
  favicon: img/favicon.ico
  name: material
  logo: img/horizontal_dark_green.png
  features: 
    - navigation.tracking
    - content.code.annotate
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
# Repository
repo_name: "GitHub"
repo_url: "https://github.com/crweiner/hacktoberfest-swag-list"
edit_uri: "https://github.com/crweiner/hacktoberfest-swag-list/edit/master/docs"

plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - social:
      cards_color:
        fill: "#2E303E"
        text: "#FFFFFF"
# Page tree
nav:
  - "Home": "index.md"
  - "Contributing": "contributing.md"
  - "2024 Hacktoberfest Swag List": "list.md"

  # Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com/crweiner"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/c_dubbs"
  analytics:
    provider: google
    property: UA-129265975-1

#Extensions
markdown_extensions:
  - attr_list
  - markdown_link_attr_modifier:
      new_tab: external_only
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences