[build]
  command = """
  pip3 install mkdocs mkdocs-material[imaging] markdown_link_attr_modifier &&
  mkdocs build --config-file mkdocs.yml
  """
  publish = "site"

[build.environment]
  PYTHON_VERSION = "3.8"